components/GothamistHeader.vue
layouts/default.vue

- add positioning to the top banner so it can cover the overlay
- position the hanging logo so it always remains between the main sections margins and doesn't stick out into the overlay zone

tweaks to the header to better handle overlay ads

---

components/Article.vue
utils/insert-ad-div.js

Uses the inserted ad code from the ember client. Some modifications were made because it's not easy in vue to render an html block from the CMS without a wrapper element, so were removing it afterwards so it works with this code. Code could potentially be rewritten to not need this but i didn't want to mess with it too much for now.
Known issues
- no tests, there are tests in the ember client that could be ported over once we got testing set up in this repo
- No handling for ads wider than the article yet

Add dynamically inserted ad to article body

---

components/Article.vue
layouts/default.vue
store/global.js

We don't control the ads directly so the goal is to hide the ad divs as soon as possible so the htl script doesn't see them and make any requests to ad networks.
I have to make this work on the default template as well (header ads), which doesn't have access to the article properties so I'm using a variable in the vuex store.

Hide ads on the article page when the article's sensitive content flag is set

---

mixins/gtm.js

realized after merging that the event name for these events should probably be set specifically to 'articleEvent' so that GTM can still do something with them. Not sure if this is all that's needed to retain all the custom dimension data etc, but we can't handle these as page views.

gtm fixes for article events

---

nuxt.config.js

Twitter card preview was complaining about the page being too large to index. I think the main reason for this is the inlined css in the prerendered SSR response.
The good news: Based on testing on squash, this reduces the size of the prerendered template by a lot by moving the css into external files and allows twitter cards to work. Pages still looks the same.
The other news: I have absolutely no idea how this change impacts overall page performance.

Don't inline css into the ssr response

---

components/Article.vue
components/SectionPage.vue
components/TagPage.vue
layouts/default.vue

Not sure on the specifics of HTL's code, but changing this just in case.

Rename class name for htl ad divs so they can't affect htl's script

---

components/Article.vue

These fields actually come from the CMS as empty strings and not null values so we want to use the more lenient OR operator here to ignore the empty strings

fix for social titles

---

layouts/default.vue
layouts/gallery.vue
nuxt.config.js

- moves ad script login out of nuxt.config and into the templates
- (less important probably) uses the skip attribute to handle the loading logic instead of a ternary

HTLBID per environment scripts

---

pages/_section/photos/_gallery.vue

This is a fix for browser back button navigation when visiting the gallery page
https://jira.wnyc.org/browse/GOTH-153

Don't add history entries when updating the gallery image parameter

---

components/Article.vue
utils/insert-ad-div.js

This should be a separate step so styles are consistent even when we don't insert ads (e.g. on articles flagged as sensitive content)

Alway unwrap the components, even when not inserting ads

---

components/VStreamfield.vue

- change attribute names to camelCase for embed, block quote and pull quote
- change block quote type value from `block-quote` to the correct `block_quote`

Fix names for block quote, pull quote, and embeds

---

components/GothamistBreakingNews.vue
components/GothamistMarketingBanners.vue
components/TagPage.vue
layouts/default.vue
nuxt.config.js
pages/index.vue

- moved breaking news banners section into separate component
- moved product marketing banners section into separate component
- moved the "magic number" in the banner api calls to config, this "1" is actually the site id in the cms. I doubt we'll ever change it but hey it's one less value that's hardcoded into strings in the code
- relocated banners when on tag page so they appear below the curated header
- messed with margins and padding to get them to look good on each template both when there are banners and when there are no banners

product banner breaking news fix

---

components/GothamistArticle.vue
components/HtmlFragment.vue
components/VStreamfield.vue
utils/insert-ad-div.js

The timing of things here still feels a little weird, might just be the way things render on localhost. But i think things are a little more consistent now.
Still going with removing the div wrapper on streamfield rich text blocks for now instead of rewriting all the styles and ad insertion logic. (the reason list styles, for example, weren't showing up was because this failed sometimes, so they were in a wrapper div and the code expects them to be children on the article body)
I moved the code to make "wrapperless" html fragments into its own component that removes the wrapper div during `beforeMount`. It looks like there's a clever way suggested by one of the vue devs to do this directly in the components `render` method, https://jsfiddle.net/Linusborg/mfqjk5hm/ but I couldn't get that …

GOTH-175 Fix for list styles not showing as well as some issues with ad loading etc

---

components/DismissibleArea.vue
components/GothamistArticle.vue
pages/_section/_article.vue

It looks like the issue in https://jira.wnyc.org/browse/GOTH-175 was caused by some weird timing with showing(?) or hiding(?) the article page donate banner based on the cookies... not sure exactly. But in any case there was some weird stuff going on there. 
The good news is for this type of component where it's halfway down the page and doesn't affect the layout, we don't even actually have a reason to handle it server side. So i've moved everything to client side cookie handling and furthermore moved all the cookie counting/expiring/reshowing/etc logic into a separate wrapper component that only handles that logic so i could learn how do that kind of thing in Vue.

GOTH-175 Refactor logic for donate banner show/hiding into component

---

components/DismissibleArea.vue
components/GothamistArticle.vue

Looks like we were close, or in any case the last changes didn't make things worse. Tried this out on the demo tag and it looks good on demo.
- Using v-show instead of v-if to hide the banner.  Kind of a workaround more than a fix. It avoids runtime dom node manipulation all together (and thus DOM errors) by just using css to show hide instead of actually adding/removing the element. Only downside is the element always exists in the page, even when we don't want to show it, but in the big picture it's not a big deal.
- Adding back a missing property that got removed in the refactor that was causing things to not work even when the error didn't happen.

GOTH-197 Fix for DOMException error when showing donate banner

---

components/TagPage.vue

https://jira.wnyc.org/browse/GOTH-193
check to see if there are no live articles and there is no custom tag page for a tag page and if so, redirect to the 404 page
looks like my auto formatter did some stuff too :)

treat empty tag pages as a 404 error

---

components/DisqusEmbed.vue
components/GothamistArticle.vue
components/GothamistFooter.vue
components/GothamistHeader.vue
mixins/newsletter.js
package-lock.json
package.json
pages/newsletter.vue

https://jira.wnyc.org/browse/GOTH-198
Adds/ cleans up tracking for the following events
- 'NTG newsletter', 'newsletter modal impression [number]', title
- 'NTG newsletter', 'newsletter signup'
- 'NTG social', 'social share', service name
- 'NTG social', 'social follow', service name (we made this one up, not part of the News Tagging Guide)
- 'NTG user', 'comment added'
This affects events on: 
- Newsletter forms in footer, article page, /newsletter page
- Share buttons in header, next to article lead asset
- Follow buttons in footer, side menu
- Disqus comment embed
BONUS: adds utm parameters to the share buttons in the header

GOTH-198 missing events

---

nginx/nginx.conf

news sitemap is at `/sitemap-news.xml` just making the rule for the year based sections a little broader to allow any alphanumeric section name instead of only a 4 digit year

Update nginx rules for news sitemap url

---

gulpfile.js
static-demo/robots.txt

When the `ENV` env var is set to `demo`, we include a demo assets folder. Since this folder is second in the array, it's processed second, so files with the same name will override existing files in the default folder.
This is a little bit inelegant in that it will publish the file at `assets/robots.txt` to S3 and then immediately update/replace it with `assets-static/robots.txt`, but it works and I think we're unlikely to use this pattern for larger files where this might matter more.
<details>
<summary>
Example of the deploy step in action on demo. Notice the second robots.txt update.
</summary>
```
[17:13:00] Using gulpfile ~/project/gulpfile.js
[17:13:00] Starting 'deploy'...
Configured with CloudFront distribution
[17:13:00] [skip]   README.md
[17:13:00] [skip]   ads.txt
[17:13:00] …
```

Deploy demo robots.txt when `ENV` is `demo`

---

circle.yml

Enable testing on CircleCI
There was a filter rule that filtered out all branches named with the "dev/feature" convention. i think this was a holdover from our ember repos where we ran a qa build task for those branches instead. Since squash is handling QA builds we want to run the test workflow on all branches and not filter those ones out

Enable testing on circle ci

---

app/router.scrollBehavior.js

By default Nuxt will automatically scroll to the top of new pages, except when using that browsers' back/forward navigation, OR on child routes... because the article route is not at the top level of the directory tree, it's considered a child route so navigating to it is retains the current scroll position.
Nuxt provides a scrollToTop property to set to true when you want to override this behavior.
https://nuxtjs.org/docs/components-glossary/scrolltotop/
**But**, this property doesn't work. There are issues about in the nuxt project and nobody seems to know why it doesn't work.
Alternatively we can override the [default nuxt scroll behavior](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/router.scrollBehavior.js) by providing a custom scrollBehavior function …

GOTH-242 Override default scroll behavior

---

components/GothamistHeader.vue
layouts/default.vue
package-lock.json
package.json

this description is the same on the DS PR:
This one is a tricky one. I will need to explain over a zoom call. 
But in a nut shell. html { scroll-padding-top: 85px; } is the issue in the default.vue and a small update in the component. 
In the DS,  VSearch.vue, I just updated the focus() to this: "this.$refs.searchInput.focus({ preventScroll: true })". This stopped the scrolling when initially clicking on the search icon and getting focus on the text field.
The reason tying in the text field scrolls the site is because it is trying to get the text field into the view port, which is currently set to be 85px ( html { scroll-padding-top: 85px; } ) from the top. But because the text field in in the sticky header, it never reaches the specified viewport. To prevent this, you have to make …

resolved, time to review with Kim

---

nuxt.config.js
plugins/features.js
plugins/sfmc-analytics.client.js
store/global.js

https://nypublicradio-digital.atlassian.net/browse/GOTH-233
- Added a new custom dimension (11) and data layer variable (`NYPRMember`) to our GTM config
- This adds a nuxt plugin that checks for the sfmc query param, or a cookie with membership status. If either exists it pushes that value to the GTM data layer and updates the cookie.

GOTH-233 SFMC Cookies/Analytics

---

.circleci/config.yml
Dockerfile

May or may not help with the current deployment issues, but it's something we should be doing anyway.
Always using a lockfile helps ensure our builds are consistent across different environments and days of the week.

Update deploy setup for more consistent builds

---

.circleci/config.yml

I noticed this flag was present, probably forgotten from some time when we needed SSH access to the cluster. Removing it now for security hygiene.

Disables ecs exec

---

components/BetaOptIn.vue
components/GothamistArticle.vue
pages/beta-opt-in.vue

- Add a route that sets the beta cookie and redirects you back to the site. Cloudfront should hand the rest.
- Adds a bet opt in module that takes you to the opt-in route
- Replaces the comment section with said module

Replace comments with beta opt in
