nypublicradio/gothamist-vue

components/GothamistFooterNewsletter.vue
components/GothamistHeader.vue
components/ReadMoreIn.vue
package-lock.json
package.json
pages/index.vue
store/global.js

read more, updated ds

---

components/GothamistHeader.vue
layouts/gallery.vue
package-lock.json
package.json
pages/_section/photos/_gallery.vue

Hey Matt! This PR is for the gallery page and includes:
1) the gallery page
2) a new gallery layout
3) an updated gothamist header that can handle the gallery page header design

Gallery Page

---

components/GothamistHeader.vue
layouts/default.vue
nuxt.config.js
package-lock.json
package.json
pages/_section/photos/_gallery.vue
pages/contact.vue

- Load HTLBid scripts and stylesheets based on environment
- Ad div for top of page Leaderboard ad (above the menu)
- Implement sticky menu behavior, the ad can scroll out of the way but the menu doesn't
- Add universal targeting rules to default layout

Base Ad Implementation

---

layouts/default.vue
pages/index.vue

Added more ad slots for the home page template.
I think I might just bundle all these wrapper divs into a little ad component but i'm going to wait until i implement the inserted ad to refactor these in case that complicates things.

Add homepage ad slots

---

components/Article.vue
mixins/gtm.js
mixins/helpers.js

Added gtm to the article page, took care of the breadcrumbs structured data ticket (https://jira.wnyc.org/browse/GOTH-46), and fixed some broken tag links I found.

Article gtm

---

components/InformationPage.vue
pages/contact.vue
pages/preview.vue

Preview functionality! I also created a component for "information page" so we can re-use it on both preview and the contact us page.

preview page

---

components/Article.vue

Loads the comment count for the byline on the article page

Set comment count for byline on article page

---

components/Article.vue
components/DisqusEmbed.vue

- Update the layout of the inserted ad so it can break out of the article margins and doesn't get cut off
- Unrelated fix for the data type of the disqus id

Fix for Inserted ad layout

---

components/DoYouKnowTheScoop.vue

We need a fix like this whenever we use an anchor link

fix for link to the comments section in the "do you know the scoop" cta module

---

components/Article.vue
components/SectionPage.vue
components/TagPage.vue
layouts/default.vue

More fixes for ads getting cut off

Add ad margin breakout styles to tag and section pages

---

components/Article.vue
pages/_section/photos/_gallery.vue
pages/contact.vue
pages/newsletter.vue
pages/search.vue
pages/staff/index.vue

- fix lead article for image
- fix social title and description overrides
- fix lead image url hardcoded to demo (it's kind of like metadata...)

Metadata fixes

---

components/Article.vue
pages/_section/_article.vue

Fixes all the problems with the donate banner cookie code

donate banner fixes

---

nuxt.config.js

I'm looking at the circle file and i'm seeing this as sometimes uppercase and sometimes lowercase in the environment so this keeps it consistent no matter what's going on.

Always convert env to lowercase

---

components/Article.vue

It's hard to tell for sure because both versions work locally but i think this will work better. Also checked it on squash and it looked good.

move sensitive content check to mounted

---

components/Article.vue
pages/_section/_article.vue

Stuff like this should probably happen at the page level anyway.

Move sensitive content check to the page component

---

static/ads.txt
static/robots.txt

Update robots.txt and add ads.txt

Update robots.txt, ads.txt

---

layouts/default.vue

- changes the api attribute references for the product and breaking news banner from snake case to camelcase to match the axios changes

Fix for breaking news and product banners

---

components/VStreamfield.vue

fix for https://jira.wnyc.org/browse/GOTH-157

check for newsletter signup and add script to page

---

components/Article.vue

fixing broken WTC breadcrumb link on article pages

fixing broken WTC breadcrumb link on article pages

---

components/GothamistArticle.vue
pages/_section/_article.vue
pages/preview.vue

rename article component to GothamistArticle so it's name doesn't conflict with the article page component

rename article component to GothamistArticle

---

components/GothamistArticle.vue

moved the comments ID out of the v-if statement, sometimes it wasn't rendering fast enough

potential fix for comment links not working on slower connections

---

components/GothamistArticle.vue

just moving some code around - need to test this on demo

scroll to comments after ad is inserted

---

circle.yml

We found the issue so we can build this again, probably

revert circle changes

---

.env.sample
components/GothamistArticle.vue
nuxt.config.js

https://jira.wnyc.org/browse/kim/GOTH-192

added amphtml tag to article head

---

mixins/helpers.js

https://jira.wnyc.org/browse/GOTH-199
updated helper function for getting article images across the site - added format JPG and 80% quality

load article images as a JPG at 80% quality

---

nginx/nginx.conf

https://jira.wnyc.org/browse/GOTH-166
- update wagtail_host to point to the correct site on demo
- update sitemap url regex to support `sitemap-####.xml` urls

nginx config updates for sitemap

---

components/GothamistArticle.vue
layouts/default.vue
mixins/gtm.js
mixins/helpers.js
pages/_slug.vue
pages/tags/_slug.vue

Fixes some moderate to severe issues i notice when looking at tracking in the console with the GA event watcher plugin (adswerve).
**Pages views logging the title and other metadata for previous page instead of current page.** 
There are lot of ways to track vue page navigation, (mounted hook, vue-meta's afterNavigation hook, etc.) but most of them run before nuxt can update the page's metadata. The only thing i found to actually work (sometimes) was wrapping the Nuxt component in a transition and using the transitions `after-enter` hook. I think it will make ad handling more consistent too. Even this doesn't work perfectly though. I see several open issues about this on the nuxt-gtm repo. Not sure there's an easy fix but i think this is working better than before at least...
**Page views …

GOTH-211 page views and milestones

---

package-lock.json
package.json
test/Breadcrumbs.test.js
test/DonateBanner.test.js
test/jest.setup.js

Clean up warnings on existing tests, deprecation messages

Clean up test output

---

circle.yml

store the test results so Circle CI can give nicer test reporting

Store test report for CircleCI

---

components/GothamistArticle.vue

https://nypublicradio-digital.atlassian.net/browse/GOTH-253

removed amphtml link meta tag from article page

---

components/RecirculationModule.vue

https://nypublicradio-digital.atlassian.net/browse/GOTH-264

remove sponsored content from recirc module

---

pages/_section/photos/_gallery.vue

https://nypublicradio-digital.atlassian.net/browse/GOTH-271

add "Photo Gallery" to title tag

---

pages/_section/photos/_gallery.vue

https://nypublicradio-digital.atlassian.net/browse/GOTH-273

added hidden H1 for gallery pages

---

components/ArticlePageNewsletter.vue
components/DoYouKnowTheScoop.vue
components/DonateBanner.vue
components/GothamistFooterNewsletter.vue
components/GothamistHeader.vue
components/HomepageDonateBanner.vue
components/ProductMarketingBanner.vue
package-lock.json
pages/newsletter.vue

adding rel='noopener noreferrer' to target _blank links per deepsource + formatting (https://nypublicradio-digital.atlassian.net/browse/GOTH-278)

deepsource security bugs

---

Dockerfile
components/GothamistArticle.vue
mixins/helpers.js
package-lock.json
package.json

https://nypublicradio-digital.atlassian.net/browse/GOTH-276
Update article page human readable metadata block (byline) with new formatting rules

GOTH-276 article dates

---

mixins/helpers.js

1-12 hours not 0-11 hours
https://date-fns.org/v2.28.0/docs/format

fix timestamp string

---

components/GothamistPlayer.vue
layouts/default.vue

Fixes a hydration issue with the a/b test of the persistent player.

Player fix

---

components/GothamistPlayer.vue

- remove player description field
- limit width of title so it doesn't encroach on buttons

Player displaty tweaks
